In [2]:
#solution 1
import numpy as np
import pandas as pd
v = np.array([1,2,3,4],dtype=int).reshape(-1,1)
N = v.shape[0]
z = np.zeros([N,N])
for i in range(len(v)):
    z[:,i:i+1]=z[:,i:i+1]+v**(N-i-1)

print(z)

[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


In [9]:
#solution2
x = np.array([1,2,3,4])
N = x.shape[0]
np.vander(x,N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

# Problem 2


In [4]:
def moving_average(a, n=3) :
 asum = np.cumsum(a, dtype=float)
 asum[n:] = asum[n:] - asum[:-n]
 return asum[n - 1:] / n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a1=np.array(a)
np.array(moving_average(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])